split project intro sub-projects
aiven/aiven-elasticsearch-repositories pull request #14
Opened 2020-08-27 13:16 UTC by willyborankin

gradle build for multi-project settings

2020-09-03 11:38 UTC, ivanyu requested changes

2020-09-03 11:38 UTC, ivanyu commented on build.gradle
> +    distributions {
Looks duplicate

2020-09-07 09:38 UTC, willyborankin commented on build.gradle
> +    distributions {
true

2020-09-07 10:49 UTC, ivanyu approved these changes
LGTM.
Do you plan to squash?

2020-09-07 12:39 UTC, willyborankin commented
@ivanyu squashed

2020-09-07 12:53 UTC, merged