Add common abstraction for plugins
aiven/aiven-elasticsearch-repositories pull request #15
Opened 2020-09-09 07:24 UTC by willyborankin

Add common abstraction for plugins, which helps to develop new one faster

2020-09-10 12:26 UTC, ivanyu commented
What do you think about changing the GCS implementation to use this new classes right away? It might highlight potential flaws in their design.

2020-09-10 12:59 UTC, willyborankin commented
@ivanyu I've done it. just split up PRs for simplicity ;-)

2020-09-14 09:30 UTC, ivanyu requested changes
One small thing to change, but overall LGTM. Let's see how it works in the real usage

2020-09-14 09:42 UTC, willyborankin commented on repository-commons/src/main/java/io/aiven/elasticsearch/repositories/RepositorySettingsProvider.java
> +            throw new IOException("Settings for GC storage hasn't been set");
true :-D

2020-09-14 09:54 UTC, willyborankin commented
@ivanyu done

2020-09-14 10:02 UTC, ivanyu approved these changes

2020-09-14 10:02 UTC, merged